INSERT INTO automation_chains (
  chain_key,
  name,
  trigger_type,
  trigger_value,
  reward_type,
  reward_value,
  delay_seconds,
  active,
  priority,
  show_in_task_hub,
  task_title,
  task_description,
  task_cycle,
  task_reward_json,
  task_reward_case_type,
  task_reward_case_count,
  task_progress_target,
  task_sort_order,
  task_starts_at,
  task_ends_at,
  task_image_url,
  task_active,
  task_repeatable,
  task_profile_xp_reward
) VALUES
  (
    'task_daily_login_1',
    'Ежедневная активность · Вход в игру',
    'daily_logins',
    1,
    'game_task',
    '/tasks',
    0,
    1,
    95,
    1,
    'Загляни в кафе',
    'Открой игру сегодня, чтобы продолжить серию и забрать награду за вход.',
    'daily',
    '[]',
    'small',
    1,
    1,
    66,
    NULL,
    NULL,
    '/assets/tasks/task_days.webp',
    1,
    1,
    6
  ),
  (
    'task_weekly_logins_5',
    'Еженедельная активность · 5 входов',
    'daily_logins',
    5,
    'game_task',
    '/tasks',
    0,
    1,
    94,
    1,
    'Вернись 5 раз за неделю',
    'Заходи в игру в течение недели и поддерживай стабильную серию.',
    'weekly',
    '[]',
    'gold',
    1,
    5,
    67,
    NULL,
    NULL,
    '/assets/tasks/task_days.webp',
    1,
    1,
    10
  ),
  (
    'task_total_logins_3',
    'Коллекция входов · 3 дня',
    'daily_logins',
    3,
    'game_task',
    '/tasks',
    0,
    1,
    93,
    1,
    '3 дня вместе с Зеффи',
    'Зайди в игру 3 раза и открой первую награду за регулярность.',
    'one_time',
    '[]',
    'small',
    1,
    3,
    68,
    NULL,
    NULL,
    '/assets/tasks/task_days.webp',
    1,
    0,
    8
  ),
  (
    'task_total_logins_7',
    'Коллекция входов · 7 дней',
    'daily_logins',
    7,
    'game_task',
    '/tasks',
    0,
    1,
    92,
    1,
    'Неделя в кафе',
    'Зайди в игру 7 раз и забери усиленную награду за активность.',
    'one_time',
    '[]',
    'gold',
    1,
    7,
    69,
    NULL,
    NULL,
    '/assets/tasks/task_days.webp',
    1,
    0,
    12
  ),
  (
    'task_total_logins_14',
    'Коллекция входов · 14 дней',
    'daily_logins',
    14,
    'game_task',
    '/tasks',
    0,
    1,
    91,
    1,
    'Две недели с Зеффи',
    'Зайди в игру 14 раз и открой престижную награду за постоянство.',
    'one_time',
    '[]',
    'mythic',
    1,
    14,
    70,
    NULL,
    NULL,
    '/assets/tasks/task_days.webp',
    1,
    0,
    18
  )
ON CONFLICT(chain_key) DO UPDATE SET
  name = excluded.name,
  trigger_type = excluded.trigger_type,
  trigger_value = excluded.trigger_value,
  reward_type = excluded.reward_type,
  reward_value = excluded.reward_value,
  delay_seconds = excluded.delay_seconds,
  active = excluded.active,
  priority = excluded.priority,
  show_in_task_hub = excluded.show_in_task_hub,
  task_title = excluded.task_title,
  task_description = excluded.task_description,
  task_cycle = excluded.task_cycle,
  task_reward_json = excluded.task_reward_json,
  task_reward_case_type = excluded.task_reward_case_type,
  task_reward_case_count = excluded.task_reward_case_count,
  task_progress_target = excluded.task_progress_target,
  task_sort_order = excluded.task_sort_order,
  task_starts_at = excluded.task_starts_at,
  task_ends_at = excluded.task_ends_at,
  task_image_url = excluded.task_image_url,
  task_active = excluded.task_active,
  task_repeatable = excluded.task_repeatable,
  task_profile_xp_reward = excluded.task_profile_xp_reward;
