// Sandbox-only illustrative prices. NOT real player balances.
// Before enabling production, validate prices on the Worker and perform atomic D1 purchases.
export const ROAD_TILE_PRICE = Object.freeze({ points: 50, coffee: 0, treats: 0 });
export const PARCEL_PRICE = Object.freeze({points: 1200, coffee: 0, treats: 10});
export const OBJECT_PRICES = Object.freeze({
  'cottage': Object.freeze({ points: 1000, coffee: 0, treats: 15 }),
  'family-home': Object.freeze({ points: 2200, coffee: 0, treats: 25 }),
  'villa': Object.freeze({ points: 4500, coffee: 0, treats: 50 }),
  'coffee-kiosk': Object.freeze({ points: 1200, coffee: 20, treats: 0 }),
  'coffee-house': Object.freeze({ points: 2800, coffee: 40, treats: 0 }),
  'bakery': Object.freeze({ points: 2000, coffee: 25, treats: 0 }),
  'flower-shop': Object.freeze({ points: 1800, coffee: 10, treats: 18 }),
  'garden': Object.freeze({ points: 1500, coffee: 0, treats: 35 }),
  'playground': Object.freeze({ points: 2200, coffee: 0, treats: 30 }),
  'tree': Object.freeze({ points: 200, coffee: 0, treats: 5 }),
  'flowerbed': Object.freeze({ points: 150, coffee: 0, treats: 3 }),
  'lamp': Object.freeze({ points: 250, coffee: 5, treats: 0 }),
  'bench': Object.freeze({ points: 350, coffee: 0, treats: 6 }),
  'fountain': Object.freeze({ points: 1800, coffee: 0, treats: 30 }),
  'monument': Object.freeze({ points: 3500, coffee: 0, treats: 60 }),
  'plaza-city-square': Object.freeze({ points: 1400, coffee: 0, treats: 12 }),
  'plaza-cozy-tiled': Object.freeze({ points: 800, coffee: 0, treats: 6 }),
  'plaza-flower-edge': Object.freeze({ points: 1100, coffee: 0, treats: 16 }),
  'plaza-monument-base': Object.freeze({ points: 1500, coffee: 0, treats: 15 }),
  'plaza-rest-zone': Object.freeze({ points: 1000, coffee: 0, treats: 12 }),
  'plaza-playground-base': Object.freeze({ points: 900, coffee: 0, treats: 8 }),
  'plaza-bordered-shrubs': Object.freeze({ points: 1300, coffee: 0, treats: 18 }),
  'plaza-prestige-podium': Object.freeze({ points: 2200, coffee: 0, treats: 24 }),
  'extra-flowerbed': Object.freeze({ points: 260, coffee: 0, treats: 6 }),
  'extra-bush': Object.freeze({ points: 140, coffee: 0, treats: 3 }),
  'extra-tree': Object.freeze({ points: 240, coffee: 0, treats: 7 }),
  'extra-lamp': Object.freeze({ points: 300, coffee: 6, treats: 0 }),
  'extra-bench': Object.freeze({ points: 420, coffee: 0, treats: 8 }),
  'extra-planter': Object.freeze({ points: 210, coffee: 0, treats: 4 }),
  'extra-arch': Object.freeze({ points: 650, coffee: 0, treats: 12 }),
  'extra-fountain': Object.freeze({ points: 1800, coffee: 0, treats: 30 }),
  'extra-sign': Object.freeze({ points: 260, coffee: 0, treats: 3 }),
  'extra-sweet_object': Object.freeze({ points: 1100, coffee: 0, treats: 22 }),
  'terrain_platform_plain_premium': Object.freeze({ points: 750, coffee: 0, treats: 8 }),
  'terrain_border_floral_premium': Object.freeze({ points: 650, coffee: 0, treats: 7 }),
  'terrain_edge_straight_a_premium': Object.freeze({ points: 450, coffee: 0, treats: 5 }),
  'terrain_edge_straight_b_premium': Object.freeze({ points: 450, coffee: 0, treats: 5 }),
  'terrain_corner_outer_premium': Object.freeze({ points: 550, coffee: 0, treats: 6 }),
  'terrain_corner_inner_premium': Object.freeze({ points: 550, coffee: 0, treats: 6 }),
  'terrain_stair_entry_premium': Object.freeze({ points: 900, coffee: 0, treats: 12 }),
  'terrain_podium_plaza_premium': Object.freeze({ points: 1800, coffee: 0, treats: 18 }),
});
