(()=>{
'use strict';
if(window.__ZC42_COFFEE_POPUP__)return;window.__ZC42_COFFEE_POPUP__=true;
const API_KEY='zc42:candidate-api';
const PLAYER_KEY='zc42:player-key';
const DEFAULT_MILESTONES=[
  {dayIndex:3,icon:'🍥',label:'250 зефира',reward:{type:'zefir',amount:250,itemId:''}},
  {dayIndex:5,icon:'⭐',label:'+500 XP сезона',reward:{type:'season_xp',amount:500,itemId:''}},
  {dayIndex:7,icon:'🎁',label:'Серебряный кейс',reward:{type:'case',amount:1,itemId:'sweet'}},
  {dayIndex:14,icon:'🏆',label:'Золотой кейс',reward:{type:'case',amount:1,itemId:'gold'}},
  {dayIndex:21,icon:'✨',label:'+1 500 XP сезона',reward:{type:'season_xp',amount:1500,itemId:''}},
  {dayIndex:28,icon:'🌟',label:'Сезонный кейс',reward:{type:'case',amount:1,itemId:'seasonal'}},
  {dayIndex:35,icon:'💜',label:'Мифический кейс',reward:{type:'case',amount:1,itemId:'mythic'}},
  {dayIndex:42,icon:'👑',label:'Легендарный кейс',reward:{type:'case',amount:1,itemId:'legendary'}}
];
let model=null, opened=false, busy=false, lastError='';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function apiBase(){const q=new URLSearchParams(location.search).get('candidate_api');const saved=localStorage.getItem(API_KEY)||'';return String(q||saved||'').trim().replace(/\/$/,'')}
function setApiBase(value){const raw=String(value||'').trim().replace(/\/$/,'');if(raw)localStorage.setItem(API_KEY,raw);else localStorage.removeItem(API_KEY);return raw}
function playerKey(){let id='';try{id=String(window.Telegram?.WebApp?.initDataUnsafe?.user?.id||'')}catch{}if(id)return `tg-${id}`;let saved=localStorage.getItem(PLAYER_KEY)||'';if(saved)return saved;try{saved='preview-'+crypto.randomUUID().replace(/-/g,'').slice(0,20)}catch{saved='preview-'+Date.now().toString(36)+Math.random().toString(36).slice(2,8)}localStorage.setItem(PLAYER_KEY,saved);return saved}
function requestId(){try{return 'daily-'+crypto.randomUUID()}catch{return 'daily-'+Date.now().toString(36)+'-'+Math.random().toString(36).slice(2)}}
function offlineModel(){return{ok:true,serverAuthoritative:false,candidate:'V4.2',serverDayKey:'—',season:{id:'offline',title:'Candidate backend не подключён',revision:0,timezoneOffsetMinutes:180},milestones:DEFAULT_MILESTONES,state:{progressDays:0,streak:0,bestStreak:0,lastActiveDayKey:'',todayCompleted:false,currentBlock:{index:1,startDay:1,endDay:7,filled:0},claimedDays:[],nextMilestone:DEFAULT_MILESTONES[0]},test:{offsetDays:0}}}
async function api(path,body={}){const base=apiBase();if(!base)throw new Error('Укажите URL отдельного Candidate V4.2 backend.');const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const r=await fetch(base+'/api/candidate/v4'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({playerKey:playerKey(),...body}),cache:'no-store',signal:controller.signal});const text=await r.text();let d={};try{d=JSON.parse(text)}catch{}if(!r.ok||d?.ok===false)throw new Error(d?.error||`Candidate server: ${r.status}`);return d}catch(e){if(e?.name==='AbortError')throw new Error('Candidate server не ответил за 8 секунд.');throw e}finally{clearTimeout(timer)}}
function streakVisual(n){if(n>=30)return['t4','✨🔥✨','Легендарная серия'];if(n>=14)return['t3','🔥🔥🔥','Большая серия'];if(n>=7)return['t2','🔥🔥','Горячая серия'];if(n>=3)return['t1','🔥','Серия разгорается'];return['',n?'✦':'○',n?'Серия началась':'Начни серию']}
function plural(n){const m=n%100,d=n%10;return m>=11&&m<=19?'дней':d===1?'день':d>=2&&d<=4?'дня':'дней'}
function ensureLayer(){let layer=document.getElementById('zc42Layer');if(layer)return layer;layer=document.createElement('div');layer.id='zc42Layer';layer.className='zc42-layer';layer.hidden=true;layer.innerHTML='<section class="zc42-card" role="dialog" aria-modal="true" aria-label="Кофейная карточка Зеффи"><div id="zc42Body"></div></section>';document.body.append(layer);layer.addEventListener('click',e=>{if(e.target===layer)close()});let launch=document.getElementById('zc42Launch');if(!launch){launch=document.createElement('button');launch.id='zc42Launch';launch.type='button';launch.className='zc42-launch';launch.textContent='☕ Карточка';launch.addEventListener('click',()=>open(true));document.body.append(launch)}return layer}
function milestoneMap(items){return new Map((items||[]).map(x=>[Number(x.dayIndex),x]))}
function currentBlock(m){const block=m?.state?.currentBlock||{index:1,startDay:1,endDay:7,filled:0};return block}
function rewardMini(item){if(!item)return'';return `<em>${esc(item.icon||'🎁')}</em>`}
function render(){const body=document.getElementById('zc42Body');if(!body)return;const m=model||offlineModel(),st=m.state||{},milestones=m.milestones||[],map=milestoneMap(milestones),claimed=new Set(st.claimedDays||[]),block=currentBlock(m),[tier,flame,label]=streakVisual(Number(st.streak||0));const slots=Array.from({length:7},(_,i)=>{const abs=block.startDay+i,done=i<Number(block.filled||0),reward=map.get(abs),isClaimed=claimed.has(abs);return `<div class="zc42-stamp ${done?'done':''} ${reward?'milestone':''} ${isClaimed?'claimed':''}"><span>${done?'🐾':'○'}</span><small>Д${abs}</small>${reward?rewardMini(reward):''}</div>`}).join('');const near=milestones.filter(x=>x.dayIndex>=Math.max(1,Number(st.progressDays||0)-1)).slice(0,6);const ladder=(near.length?near:milestones.slice(-6)).map(x=>`<div class="zc42-milestone ${claimed.has(Number(x.dayIndex))?'claimed':''} ${Number(st.progressDays||0)>=Number(x.dayIndex)?'reached':''}"><b>${x.dayIndex} день</b><strong>${esc(x.icon||'🎁')} ${esc(x.label||'Награда')}</strong></div>`).join('');const next=st.nextMilestone;const connected=Boolean(m.serverAuthoritative);const serverText=connected?`SERVER · ${esc(m.season?.title||'')} · rev ${Number(m.configRevision||m.season?.revision||0)}`:'SERVER OFFLINE · только макет расписания';const today=connected?(st.todayCompleted?'🐾 Сегодняшняя активность уже засчитана сервером.':'🏃 Заверши один забег сегодня — сервер засчитает следующий активный день.'):'⚠️ Подключи отдельный Candidate backend, чтобы прогрессом управлял сервер.';body.innerHTML=`
<div class="zc42-head"><div class="zc42-icon">☕</div><div><h2>Кофейная карточка Зеффи</h2><p>Награды растут по дням активности. Пропуск не стирает прогресс, но прерывает серию.</p></div><button class="zc42-close" data-zc-close type="button">×</button></div>
<div class="zc42-server ${connected?'on':'off'}"><span>${connected?'●':'○'}</span><b>${serverText}</b><small>Игровой день: ${esc(m.serverDayKey||'—')}</small></div>
<div class="zc42-streak ${tier}"><div class="zc42-streak-main"><div class="zc42-flame">${flame}</div><div><b>${st.streak?`${st.streak} ${plural(st.streak)}`:'Нет серии'}</b><small>${label}</small></div></div><div class="zc42-best">Лучшая серия<strong>${Number(st.bestStreak||0)} 🔥</strong></div></div>
<div class="zc42-progress-head"><div><b>День активности ${Number(st.progressDays||0)}</b><span>Неделя ${Number(block.index||1)} · дни ${block.startDay}–${block.endDay}</span></div><strong>${Number(block.filled||0)} / 7</strong></div>
<div class="zc42-stamps">${slots}</div><div class="zc42-progress"><i style="width:${Math.min(100,Math.max(0,Number(block.filled||0)/7*100))}%"></i></div>
<div class="zc42-next"><div>${next?esc(next.icon||'🎁'):'🏁'}</div><div><b>${next?`Следующая награда — ${next.dayIndex} день`:'Все настроенные награды получены'}</b><span>${next?esc(next.label||''):'В CC Candidate можно добавить 35, 42, 56 день и дальше.'}</span></div></div>
<div class="zc42-ladder-title">Прогрессия наград</div><div class="zc42-ladder">${ladder||'<span>Награды не настроены</span>'}</div>
<div class="zc42-today">${today}</div>
${lastError?`<div class="zc42-error">${esc(lastError)}</div>`:''}
<div class="zc42-actions"><button class="zc42-btn" data-zc-run ${!connected||busy||st.todayCompleted?'disabled':''}>${busy?'Подождите…':'🧪 Засчитать успешный забег'}</button><button class="zc42-btn secondary" data-zc-close>Закрыть</button></div>
<details class="zc42-test"><summary>🧪 Управление Candidate / сервер</summary><div class="zc42-test-body"><label>URL отдельного Candidate backend</label><div class="zc42-url"><input data-zc-api value="${esc(apiBase())}" placeholder="https://...workers.dev"><button data-zc-save-api>Подключить</button></div><small>Production Worker и Production D1 не используются.</small><div class="zc42-test-grid"><button data-zc-preset="3" ${!connected?'disabled':''}>3 🔥</button><button data-zc-preset="7" ${!connected?'disabled':''}>7 🔥🔥</button><button data-zc-preset="14" ${!connected?'disabled':''}>14 🔥🔥🔥</button><button data-zc-preset="30" ${!connected?'disabled':''}>30 ✨🔥✨</button><button data-zc-next ${!connected?'disabled':''}>+1 день и активность</button><button data-zc-miss ${!connected?'disabled':''}>Пропустить день</button></div><div class="zc42-test-grid two"><button data-zc-reset ${!connected?'disabled':''}>Сбросить игрока</button>${connected?`<a href="${esc(apiBase())}/admin" target="_blank" rel="noopener">⚙️ Награды / сезоны</a>`:''}</div></div></details>
<div class="zc42-foot">Candidate V4.2 · сервер является источником истины. Reward claims остаются только в Candidate ledger и не меняют Production-экономику.</div>`;
body.querySelectorAll('[data-zc-close]').forEach(b=>b.addEventListener('click',close));body.querySelector('[data-zc-run]')?.addEventListener('click',runActivity);body.querySelector('[data-zc-save-api]')?.addEventListener('click',async()=>{const v=setApiBase(body.querySelector('[data-zc-api]')?.value||'');lastError='';if(!v){model=offlineModel();render();return}await refresh(true)});body.querySelector('[data-zc-next]')?.addEventListener('click',nextActive);body.querySelector('[data-zc-miss]')?.addEventListener('click',missDay);body.querySelector('[data-zc-reset]')?.addEventListener('click',resetPlayer);body.querySelectorAll('[data-zc-preset]').forEach(b=>b.addEventListener('click',()=>preset(Number(b.dataset.zcPreset))));}
async function refresh(showError=false){if(!apiBase()){model=offlineModel();render();return model}busy=true;render();try{model=await api('/daily/bootstrap');lastError='';return model}catch(e){model=offlineModel();lastError=String(e?.message||e);if(showError)console.warn('Candidate daily bootstrap',e);return model}finally{busy=false;render()}}
async function mutate(fn){if(busy)return;busy=true;lastError='';render();try{const result=await fn();model=result;if(Array.isArray(result?.grantedRewards)&&result.grantedRewards.length){const txt=result.grantedRewards.map(x=>`${x.icon||'🎁'} ${x.label||'Награда'}`).join(' · ');toast(`Получено в Candidate: ${txt}`)}}catch(e){lastError=String(e?.message||e)}finally{busy=false;render()}}
async function runActivity(){if(model?.serverAuthoritative&&model?.state?.todayCompleted)return model;return mutate(()=>api('/daily/activity',{requestId:requestId()}))}
async function nextActive(){return mutate(async()=>{await api('/test/advance',{days:1});return api('/daily/activity',{requestId:requestId()})})}
async function missDay(){return mutate(()=>api('/test/advance',{days:2}))}
async function resetPlayer(){return mutate(()=>api('/test/reset'))}
async function preset(days){return mutate(()=>api('/test/preset',{days}))}
function toast(text){let t=document.getElementById('zc42Toast');if(!t){t=document.createElement('div');t.id='zc42Toast';t.className='zc42-toast';document.body.append(t)}t.textContent=text;t.classList.add('show');clearTimeout(t._timer);t._timer=setTimeout(()=>t.classList.remove('show'),2600)}
async function open(force=false){ensureLayer();const layer=document.getElementById('zc42Layer');layer.hidden=false;document.documentElement.classList.add('zc42-open');document.body.classList.add('zc42-open');if(force||!model)await refresh(false);else render();opened=true}
function close(){const layer=ensureLayer();layer.hidden=true;document.documentElement.classList.remove('zc42-open');document.body.classList.remove('zc42-open')}
function gameReady(){const game=document.querySelector('iframe');return Boolean(game?.dataset?.activated==='1'&&game.classList.contains('is-ready')&&!document.querySelector('.zefirok-legal-gate')&&!document.querySelector('.zefirok-maintenance-gate')&&!document.querySelector('.zefirok-legal-layer'))}
function auto(){ensureLayer();if(!opened&&gameReady()){opened=true;setTimeout(()=>open(true),240);return true}return false}
window.addEventListener('message',event=>{const game=document.querySelector('iframe');if(event.source!==game?.contentWindow||event.data?.type!=='zefirok:candidate:run-settled')return;if(!apiBase())return;runActivity();});window.addEventListener('zefirok:candidate:legal-complete',()=>setTimeout(()=>open(true),180));document.addEventListener('DOMContentLoaded',()=>{ensureLayer();let tries=0;const t=setInterval(()=>{tries++;if(auto()||tries>160)clearInterval(t)},100)});if(document.readyState!=='loading'){ensureLayer();setTimeout(auto,0)}
})();
